export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_RESET_ERROR = 'AUTH_RESET_ERROR';
export const AUTH_GET_LISTS = 'AUTH_GET_LISTS';
export const DISABLE_ADD_TASK_START = 'DISABLE_ADD_TASK_START';
export const DISABLE_ADD_TASK_SUCCESS = 'DISABLE_ADD_TASK_SUCCESS';
export const SET_CURRENT_LIST = 'SET_CURRENT_LIST';

